# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kepfeltolto', '0004_auto_20160902_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='Kepfeltolto.Profile'),
        ),
    ]
