# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kepfeltolto', '0005_auto_20160902_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
